CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py, HT/partitioned-heat/fenics-fenics/heat.py
related to [PR #6 in precice/fenics-adapter](https://github.com/precice/fenics-adapter/pull/6).
=> Updated tutorials w.r.t changes introduced in PR #6 in precice/fenics-adapter

HT/partitioned-heat/fenics-fenics/tools/g_pol_setup_c_sdc_cubic.sh, HT/partitioned-heat/fenics-fenics/tools/g_pol_setup_qrt_sdc_cubic.sh, HT/partitioned-heat/fenics-fenics/tools/g_pol_setup_qrt_sdc_quartic.sh
=> reduce number of timestep sizes being run

FSI/cylinderFlap/OpenFOAM-deal.II/README.md, FSI/cylinderFlap_2D/OpenFOAM-deal.II/README.md, FSI/flap_perp/OpenFOAM-deal.II/README.md, FSI/flap_perp_2D/OpenFOAM-deal.II/README.md
=> Add missing deal.II README files

HT/partitioned-heat/fenics-fenics/precice-adapter-config-D.json, HT/partitioned-heat/fenics-fenics/precice-adapter-config-N.json
Tutorial now uses new SegregatedRBFInterpolationExpression from https://github.com/precice/fenics-adapter/pull/83
=> Use SegregatedRBFInterpolationExpression for partitioned heat equation tutorial.

CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
This PR updates CHT/flow-over-plat to use the same method for flux computataion like https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics.
=> Use same method for flux computation like in HT example.

flow-over-heated-plate/solid-nutils/solid.py, partitioned-heat-conduction/nutils/heat.py
@BenjaminRodenberg looks good?
I tested both cases already. The vtk logging is then screwed up, but that's not soo critical here.
=> Extend checkpointing in nutils cases to subcycling

.github/workflows/checks.yaml, flow-over-heated-plate-steady-state/solid-codeaster/run.sh, quickstart/solid-cpp/clean.sh
All scripts in this repository should now be succeeding [shellcheck](https://github.com/koalaman/shellcheck). This adds a GitHub action to check our scripts for new problems.
=> Add a shellcheck action

flow-over-heated-plate/README.md
=> Add Nutils to list of available solvers

partitioned-heat-conduction/fenics/run.sh, partitioned-heat-conduction/nutils/run.sh
Nothing happens if no argument was provided, which is a bit unfortunate for people like me who are too lazy to read our documentation. This would be an easy fix.
=> Throw error in fenics and nutils run scripts if no argument was provided 

.github/workflows/update-website.yml
This PR adds a trigger to update the website submodules.
This will be triggered by any change to `.md` files and `images/` in case folders.
=> Add workflow to update website

channel-transport-reaction/README.md
Follow-up from https://github.com/precice/tutorials/pull/305#issuecomment-1317138099
=> Update channel reaction README

partitioned-heat-conduction/README.md
* Update broken link
* Remove redundancy for less maintainment
=> Fix broken link and minor update

changelog-entries/321.md, elastic-tube-3d/precice-config.xml, partitioned-elastic-beam/precice-config.xml
... as required by https://github.com/precice/precice/pull/1536
=> Remove mapping timings

elastic-tube-1d/fluid-cpp/CMakeLists.txt, elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp, elastic-tube-1d/solid-cpp/CMakeLists.txt, elastic-tube-1d/solid-cpp/src/SolidSolver.cpp
- Updates elastic-tube-1d/solid-cpp
- Updates elastic-tube-1d/fluid-cpp
=> Update elastic-tube-1d cpp solvers

.gitattributes, flow-over-heated-plate/reference-output.tar.gz, flow-over-heated-plate/tests/docker-compose.yml
I integrated fieldcompare into the docker-compose services and also added a sample reference output via git lfs to compare the results to.
=> Add nightly tests/add field compare

oscillator/python/oscillator.py
Updates the oscillator case to the latest state of the preCICE v3 API (https://github.com/precice/python-bindings/commit/166c6e10a92049ef37f7caeba83d1899f358ac92 etc.)
=> oscillator: update to v3 API

aste-turbine/precice-config.xml, changelog-entries/331.md, channel-transport/precice-config.xml, partitioned-heat-conduction/precice-config.xml, perpendicular-flap/precice-config.xml, quickstart/precice-config.xml, turek-hron-fsi3/precice-config.xml, volume-coupled-diffusion/precice-config.xml
=> Port rbf mapping configurations to preCICE v3

aste-turbine/precice-config.xml, channel-transport-reaction/precice-config.xml, channel-transport/precice-config.xml, elastic-tube-1d/precice-config.xml, elastic-tube-3d/precice-config.xml, flow-over-heated-plate-nearest-projection/precice-config.xml, flow-over-heated-plate-partitioned-flow/precice-config.xml, flow-over-heated-plate-steady-state/precice-config.xml, flow-over-heated-plate-two-meshes/precice-config.xml, flow-over-heated-plate/precice-config.xml, heat-exchanger-simplified/precice-config.xml, heat-exchanger/precice-config.xml, multiple-perpendicular-flaps/precice-config.xml, oscillator/precice-config.xml, partitioned-backwards-facing-step/precice-config.xml, partitioned-elastic-beam/precice-config.xml, partitioned-heat-conduction-complex/precice-config.xml, partitioned-heat-conduction-direct/precice-config.xml, partitioned-heat-conduction/precice-config.xml, partitioned-pipe/precice-config.xml, perpendicular-flap/precice-config.xml, quickstart/precice-config.xml, turek-hron-fsi3/precice-config.xml, volume-coupled-diffusion/precice-config.xml
Related to https://github.com/precice/precice/pull/1683
=> Rename m2n attributes to `connector` and `acceptor`

tools/tests/component-templates/openfoam-adapter.yaml, tools/tests/docker-compose.field_compare.template.yaml, tools/tests/docker-compose.template.yaml
This PR fixes #359 
I removed the user mapping and modified the corresponding docker file to use the user `USER precice` which will then also be used to run the container
=> Fixed docker user problems in openfoam-adapter

aste-turbine/precice-config.xml, channel-transport-reaction/precice-config.xml, channel-transport/precice-config.xml, elastic-tube-1d/precice-config.xml, elastic-tube-3d/precice-config.xml, flow-over-heated-plate-nearest-projection/precice-config.xml, flow-over-heated-plate-partitioned-flow/precice-config.xml, flow-over-heated-plate-steady-state/precice-config.xml, flow-over-heated-plate-two-meshes/precice-config.xml, flow-over-heated-plate/precice-config.xml, heat-exchanger-simplified/precice-config.xml, heat-exchanger/precice-config.xml, multiple-perpendicular-flaps/precice-config.xml, oscillator/precice-config.xml, partitioned-backwards-facing-step/precice-config.xml, partitioned-elastic-beam/precice-config.xml, partitioned-heat-conduction-complex/precice-config.xml, partitioned-heat-conduction-direct/precice-config.xml, partitioned-heat-conduction/precice-config.xml, partitioned-pipe/precice-config.xml, perpendicular-flap/precice-config.xml, quickstart/precice-config.xml, turek-hron-fsi3/precice-config.xml, volume-coupled-diffusion/precice-config.xml
Porting the tutorials to the latest changes coming to preCICE v3, as follow-up of https://github.com/precice/precice/pull/1742
=> Move dimensions to each mesh

flow-over-heated-plate/solid-nutils/solid.py, partitioned-heat-conduction-direct/nutils/heat.py, partitioned-heat-conduction/nutils/heat.py, partitioned-heat-conduction/precice-config.xml, perpendicular-flap/fluid-nutils/fluid.py
Closes #369 
@IshaanDesai could you please check the diff and check that it makes sense? Not having a compiler to watch my back stresses me a bit.
@davidscn I got a bit confused with the following regarding direct mesh access:
- I need to call `initialize()` before I can access the region, but
- I now need to write data to the region before I call `initialize()`, since we have merged it with `initialize_data()`.
What do I misunderstand?
Please have a look at the `partitioned-heat-conduction-direct` case. Does the order of calls around initialization make sense?
All cases work on my system and the results look reasonable.
=> Port nutils cases to preCICE v3

partitioned-pipe/precice-config.xml
* Remove unused `velocityGradient`
* Comment out `pressureGradient` to make config valid (related to https://github.com/precice/precice/issues/1803)
=> Cleanup partitioned-pipe tutorial

multiple-perpendicular-flaps/precice-config.xml, turek-hron-fsi3/precice-config.xml
..which is no longer supported IIRC
=> Remove extrapolation order from config files

.pre-commit-config.yaml, aste-turbine/precice-config.xml, channel-transport-reaction/precice-config.xml, elastic-tube-1d/precice-config.xml, flow-over-heated-plate-nearest-projection/precice-config.xml, flow-over-heated-plate-partitioned-flow/precice-config.xml, flow-over-heated-plate-steady-state/precice-config.xml, flow-over-heated-plate-two-meshes/precice-config.xml, flow-over-heated-plate/precice-config.xml, heat-exchanger-simplified/precice-config.xml, heat-exchanger/precice-config.xml, multiple-perpendicular-flaps/precice-config.xml, oscillator/precice-config.xml, partitioned-backwards-facing-step/precice-config.xml, partitioned-heat-conduction-complex/precice-config.xml, partitioned-pipe/precice-config.xml, quickstart/precice-config.xml, turek-hron-fsi3/precice-config.xml, two-scale-heat-conduction/precice-config.xml, volume-coupled-diffusion/precice-config.xml, volume-coupled-flow/precice-config.xml
- Do we want to enforce this? 
- Should we also add our preCICE pre-commit hook here?
=> Format our config files according to v3

.github/workflows/run_testsuite_manual.yml
This PR fixes a bug where no artifacts are uploaded even though requests in the manual triggering
=> Hotfix Passing of arguments

perpendicular-flap/README.md, perpendicular-flap/solid-nutils/clean.sh, perpendicular-flap/solid-nutils/run.sh, perpendicular-flap/solid-nutils/solid.py
#431 directly went to master as it still used preCICE v2. Backporting to develop here including formatting and v3.
=> Backport 431 to develop and update to v3

tools/tests/README.md
This documents the exact workflow to run the current system tests for the preCICE v3 release.
=> Document running the system tests for a preCICE release

flow-over-heated-plate-partitioned-flow/README.md, partitioned-backwards-facing-step/README.md, partitioned-pipe-two-phase/README.md, partitioned-pipe/README.md
Related to the OpenFOAM adapter release v1.3.0.
closes #446.
=> Remove notes regarding unreleased versions

elastic-tube-3d/solid-fenics/solid.py, perpendicular-flap/solid-fenics/solid.py
See #504.
Replacing `nabla_div` and `nabla_grad` with `div` and `grad`.
=> Fix ufl compatibility issues for `perpendicular-flap/solid-fenics` and `elastic-tube-3d/solid-fenics`
