- FSI/flap_perp/OpenFOAM-CalculiX/runFluid
The function getNumberOfProcessors needs to be called in the Fluid directory to work properly. I am running the script with openfoam 5 (.org version). Can you confirm this? Is it different for .com version?
> Fix runFluid -parallel error

- HT/partitioned-heat/fenics-fenics/heat.py
- HT/partitioned-heat/fenics-fenics/my_enums.py
- HT/partitioned-heat/fenics-fenics/precice-config.xml
- HT/partitioned-heat/fenics-fenics/problem_setup.py
The current heat transfer fenics-fenics tutorial consists of one case in which the interface is a straight edge parallel to the y-axis. A more generalised case of an interface of circular shape is being added in the same tutorial. User can select between two options `simple-interface` and `complex-interface` to compute the respective cases. The aim of this PR is also to verify the nearest_projection mapping implemented in this PR: https://github.com/precice/fenics-adapter/pull/42
> Adding complex interface case in HT fenics-fenics tutorial

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/precice-config_serial.xml
- CHT/flow-over-plate/buoyantPimpleFoam-nutils/precice-config.xml
- CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/precice-config_parallel.xml
- CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/precice-config_serial.xml
- FSI/3D_Tube/OpenFOAM-CalculiX/precice-config_parallel.xml
- FSI/3D_Tube/OpenFOAM-CalculiX/precice-config_serial.xml
- FSI/cylinderFlap/OpenFOAM-CalculiX/precice-config_parallel.xml
- FSI/cylinderFlap/OpenFOAM-CalculiX/precice-config_serial.xml
- FSI/cylinderFlap/OpenFOAM-FEniCS/precice-config_serial.xml
- FSI/cylinderFlap/OpenFOAM-deal.II/precice-config_parallel.xml
- FSI/cylinderFlap/OpenFOAM-deal.II/precice-config_serial.xml
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config_parallel.xml
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config_serial.xml
- FSI/flap_perp/OpenFOAM-CalculiX/precice-config_parallel.xml
- FSI/flap_perp/OpenFOAM-CalculiX/precice-config_serial.xml
- FSI/flap_perp/OpenFOAM-FEniCS/precice-config_serial.xml
- FSI/flap_perp/OpenFOAM-deal.II/precice-config_parallel.xml
- FSI/flap_perp/OpenFOAM-deal.II/precice-config_serial.xml
- FSI/flap_perp/SU2-CalculiX/precice-config_parallel.xml
- FSI/flap_perp/SU2-CalculiX/precice-config_serial.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config_parallel.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config_serial.xml
- HT/partitioned-heat/fenics-fenics/precice-config.xml
- SSI/loaded_beam/CalculiX-CalculiX/precice-config.xml
- Structure/precice-config.xml
This PR applies the same logging configuration and format to all tutorials:
```xml
<log>
<sink filter= "%Severity% >= debug" format="---[precice] %ColorizedSeverity% %Message%" enabled="true" />
</log>
```
Notes:
- Now the preCICE messages will be prepended by `---[precice] `, making them easier to identify. The same style is already used in the OpenFOAM adapter and should be extended to the rest of the adapters (see #41).
- I did not set the (default) `type="stream"` and `output="stdout"` to make the scripts user-fliendlier.
Closes #41.
> Consistent log config and format for all cases

- CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py
- CHT/flow-over-plate/buoyantPimpleFoam-nutils/README.md
Ensures compatibility to https://github.com/precice/precice/pull/576.
Related to https://github.com/precice/systemtests/pull/123, https://github.com/precice/fenics-adapter/pull/55
> Update CHT/flow-over-plate/buoyantPimpleFoam-nutils to use python bindings 2.0.0

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/precice-config.xml
- CHT/flow-over-plate/buoyantPimpleFoam-nutils/precice-config.xml
- CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/precice-config.xml
- FSI/3D_Tube/OpenFOAM-CalculiX/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-CalculiX/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-FEniCS/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-deal.II/precice-config.xml
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp/OpenFOAM-CalculiX/precice-config.xml
- FSI/flap_perp/OpenFOAM-FEniCS/precice-config.xml
- FSI/flap_perp/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp/SU2-CalculiX/precice-config.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
- HT/partitioned-heat/fenics-fenics/precice-config.xml
- SSI/loaded_beam/CalculiX-CalculiX/precice-config.xml
This PR changes all of the tutorial config files. `timestep-length` is changed to `time-window-size` and `timestep` to `time-window` (according to  https://github.com/precice/precice/pull/619#issuecomment-578889853) from PR https://github.com/precice/precice/pull/619
> Updates config files and fixes API compatibility

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/precice-config.xml
- CHT/flow-over-plate/buoyantPimpleFoam-nutils/precice-config.xml
- CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/precice-config.xml
- FSI/3D_Tube/OpenFOAM-CalculiX/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-CalculiX/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-FEniCS/precice-config.xml
- FSI/cylinderFlap/OpenFOAM-deal.II/precice-config.xml
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp/OpenFOAM-CalculiX/precice-config.xml
- FSI/flap_perp/OpenFOAM-FEniCS/precice-config.xml
- FSI/flap_perp/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp/SU2-CalculiX/precice-config.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
- HT/partitioned-heat/fenics-fenics/precice-config.xml
- SSI/loaded_beam/CalculiX-CalculiX/precice-config.xml
Previously, we explicitly printed INFO statements only for rank 0. This changed with v2.0. Now, instead we set the default of the logger to rank 0. The default gets however overwritten as soon as you set a different logger. So, the logger here also needs to restrict to rank 0 to not have INFO statements for every rank. 
Reviewer: FYI, please try with any arbitrary tutorial (I ran OpenFOAM-Nutils), and merge.
> Restrict logger to rank 0 to cope with preCICE v2.0

- FSI/cylinderFlap/OpenFOAM-deal.II/precice-config.xml
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
This removes the `<export:vtk directory="coupling_data" />` from the deal.II FSI tutorials.
@DavidSCN I would just remove them, but maybe you have reasons to keep them that I oversee. If you agree, please merge.
> Remove vtk exports from deal.II tutorials

- FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config.xml
- FSI/flap_perp_2D/OpenFOAM-deal.II/precice-config.xml
preCICE v2.1.0 is now stricter in checking that everything has the same dimensions. Our current 2D tutorials are, therefore, failing by definition.
This removes the z-component of the watchpoint in the OpenFOAM-deal.II 2D tutorials.
@DavidSCN @Eder-K maybe this is interesting for you.
> Update 2D tutorials to define 2D watchpoint

- FSI/3D_Tube/OpenFOAM-CalculiX/Fluid/system/fvSolution
- FSI/cylinderFlap/OpenFOAM-CalculiX/Fluid/system/fvSolution
- FSI/cylinderFlap/OpenFOAM-FEniCS/Fluid/system/fvSolution
- FSI/cylinderFlap/OpenFOAM-deal.II/Fluid/system/fvSolution
- FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/fvSolution
Instead, offer commented-out ways to get the residualControl in the various OpenFOAM versions, with the current values.
This may affect convergence, but the purpose of the tutorial is to demonstrate how to configure preCICE and the adapters.
This fixes #40.
> cylinderFlap OpenFOAM: Remove residualControl, version-specific

- FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/cyl-flap.py
- FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
- HT/partitioned-heat/fenics-fenics/heat.py
Ensures compatibility with changes introduced in https://github.com/precice/fenics-adapter/pull/81.
> Update FEniCS cases data initialization

- FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/precice-adapter-config-fsi-s.json
- FSI/flap_perp/OpenFOAM-FEniCS/Solid/precice-adapter-config-fsi-s.json
- HT/partitioned-heat/fenics-fenics/precice-adapter-config-D.json
- HT/partitioned-heat/fenics-fenics/precice-adapter-config-N.json
Ensures compatibility with changes introduced in https://github.com/precice/fenics-adapter/pull/86.
> Removes interpolation_type from all fenics adapter config files.

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
- FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/cyl-flap.py
- FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
- HT/partitioned-heat/fenics-fenics/heat.py
> Convert fenics.Constant to float

- CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py
If the system tests only use the coupling vtks this should have no effect. It's a pure visualization problem ... results were just lagging by one timestep. 
@Eder-K  Anything we need to adjust in the system tests or can I just merge?
> Fix wrong visualization in nutils cht.py

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
- FSI/cylinderFlap/OpenFOAM-FEniCS/Solid/cyl-flap.py
- FSI/flap_perp/OpenFOAM-FEniCS/Solid/perp-flap.py
- HT/partitioned-heat/fenics-fenics/heat.py
The initialization signature of the FEniCS-Adapter is changed in https://github.com/precice/fenics-adapter/pull/101. Correspondingly all FEniCS tutorials need to use the new initialization.
Not to be merged before https://github.com/precice/fenics-adapter/pull/101
> Change FEniCS tutorials to handle new initialization signature of FEniCS-Adapter

- CHT/flow-over-plate/buoyantPimpleFoam-fenics/Solid/heat.py
This is the actually correct fix for the bug mentioned in #126.
With this fix we do not have to change the OpenFOAM side of the simulation, which expects a scalar valued flux. We now provide a subspace of the vector valued function space `V_g` as `write_object`. `V_g.sub(1)` is scalar and we can still write the scalar valued flux `flux_y`.
> Initialize with V_g.sub(1) as write_object

- FSI/flap_perp_2D/OpenFOAM-FEniCS/Allclean
- FSI/flap_perp_2D/OpenFOAM-FEniCS/Solid/perp-flap.py
- FSI/flap_perp_2D/SU2-FEniCS/Solid/perp-flap.py
This PR introduces minor changes to FEniCS scripts for perpendicular flap cases coupled with OpenFOAM and SU2, to ensure consistency.
> Ensuring consistency in FEniCS scripts for FSI tutorial cases 

- HT/partitioned-heat/fenics-fenics/heat.py
This PR fixes an issue related to the complex geometry setup of the `HT/partitioned-heat/fenics-fenics` tutorial.
See https://github.com/precice/fenics-adapter/issues/113 for the underlying issue.
> Fix ill-posed problem by providing additional data.

- .github/workflows/checks.yaml
- tools/checkimages.sh
- tools/checkpermalinks.sh
This workflow adds a basic check for tutorials:
* permalinks of pages have to start with `tutorials-NAME` (this allows `tutorials-epic.html`, but also `tutorials-epic-introduction.html`)
* image names have to strart with `tutorials-NAME-`
This currently ignores the quickstart.
> Add checks for permalinks and image names

- tools/cleaning-tools.sh
- tools/openfoam-remove-empty-dirs.sh
In #169, I created some function-only files with tools to clean tutorial cases and to remove obsolete OpenFOAM directories. Trying to follow "safety first", I set `-e -u` in every script, including the function ones. This made it very unpractical to source globally.
I now moved these options inside each function.
This means that one can now source these scripts in their `~/.bashrc`:
```
source /path/to/tools/cleaning-tools.sh
source /path/to/tools/openfoam-remove-empty-dirs.sh
```
and use them from inside the directory which they want to clean as:
```
clean_tutorial
clean_openfoam
...
openfoam_remove_empty_dirs
```
Tab-completion also works.
I am not sure where to document this.
@DavidSCN does this close #179 for you? I tried once more making the scripts runnable from any path, but I …
> Make cleaning scripts less strict

- heat-exchanger/fluid-inner-openfoam/system/preciceDict
- heat-exchanger/fluid-outer-openfoam/system/preciceDict
- heat-exchanger/precice-config.xml
- heat-exchanger/solid-calculix/config.yml
To make it consistent with the folder names:
* fluid-inner-openfoam
* fluid-outer-openfoam
> Fix inconsistent naming in heat exchanger

- .github/workflows/check-links.yml
- .github/workflows/check-markdown.yml
- .github/workflows/check-scripts.yaml
- .markdown-link-check-config.json
- .markdownlint.json
- CONTRIBUTING.md
- elastic-tube-1d/README.md
- elastic-tube-3d/README.md
- flow-over-heated-plate-nearest-projection/README.md
- flow-over-heated-plate-steady-state/README.md
- flow-over-heated-plate/README.md
- heat-exchanger/README.md
- multiple-perpendicular-flaps/README.md
- partitioned-elastic-beam/README.md
- partitioned-pipe/README.md
- perpendicular-flap/README.md
- quickstart/README.md
- turek-hron-fsi3/README.md
Similarly to https://github.com/precice/openfoam-adapter/pull/169, this adds a GitHub action to check Markdown files for common issues and another GitHub action to check for dead links.
Following a decision we recently had, this replaces all relative links to precice.org with static ones.
> Add GitHub actions to check Markdown files and links

- .github/ISSUE_TEMPLATE/issue-template.md
- .github/pull_request_template.md
- .github/workflows/check-markdown.yml
- CODE_OF_CONDUCT.md
This adds the following long-overdue files (as previously decided):
- `CODE_OF_CONDUCT.md` - [Contributor Covenant](https://www.contributor-covenant.org/)
- Pull request template, pointing to `CONTRIBUTING.md` (which points to [contribute to preCICE](https://precice.org/community-contribute-to-precice.html)).
- Issue template, pointing to our community channels and asking for versions
Part of the motivation: tick all the boxes in the [Community insights](https://github.com/precice/tutorials/community). Another part: guide the users better.
@uekerman check the templates and merge if everything looks fine.
> Add community-related files

- quickstart/README.md
This bumps the following in our Quickstart page:
- preCICE v2.2.0 --> v2.2.1 This is still hard-coded, as it is not part of the website repository. It anyway also links to related resources, but it is arguable. Our policy is still unclear here, but if I follow the same principle as we use for hyperlinks, the tutorials repository should be readable without the website. @uekerman what do you think?
- OpenFOAM v2012 --> v2106.
> Bump versions in Quickstart

- .github/workflows/check-links.yml
- .markdown-link-check-config.json
- .markdown-lint-check-config.json
Several websites are returning e.g. `403: Forbidden` as a protection measure against denial-of-service attacks. This could also mean that indeed a link stopped working.
To distinguish between these two reasons is rather difficult, if not impossible in this context. Therefore, instead ofconsidering all 403 as `alive`, this ignores specific domains that are known to follow this practice. Meaning, indeed, that we will not be checking these links automatically.
Previously, there was also a typo in the name of the configuration file, which is probably why `403` was not being ignored completely. Happy coincidence to notice it now.
To save some unnecessary requests, the action now runs only once per week, every Sunday at midnight.
@IshaanDesai do you understand this change? Did you notice any …
> Action to check links: ignore domains that are known to return 403

- flow-over-heated-plate/README.md
Related to #226. Currently the density is missing. This is no problem for OpenFOAM, where density defaults to 1kg/m^3 (see https://github.com/precice/tutorials/issues/226#issuecomment-888344050), but for other solvers (e.g. ELMER), where the density must be specified by the user.
* Do we also need density for the solid solver? Let's try to solver this in #226.
> flow-over-heated-plate: Add density and pressure to problem parameters

- flow-over-heated-plate-steady-state/solid-codeaster/run.sh
Reported by the latest shellcheck as
```
Notice: ./flow-over-heated-plate-steady-state/solid-codeaster/run.sh:10:22: note: Double quote to prevent globbing and word splitting. [SC2086]
```
e.g., in https://github.com/precice/tutorials/runs/4455201577?check_suite_focus=true
> Fix shellcheck notice on solid-codeaster/run.sh

- .github/workflows/check-links.yml
Same motivation and implementation as in https://github.com/precice/openfoam-adapter/pull/215.
Already right now, `master` reports as `failed` because the cron job failed at some point.
> Convert check links to manual

- changelog-entries/234.md
- flow-over-heated-plate-nearest-projection/fluid-openfoam/constant/thermophysicalProperties
- flow-over-heated-plate-steady-state/fluid-openfoam/constant/thermophysicalProperties
- flow-over-heated-plate/fluid-openfoam/constant/thermophysicalProperties
See https://github.com/precice/tutorials/issues/226#issuecomment-896933844: From my current perspective, we do not need `nMoles`.
> flow-over-heated-plate: Remove unnecessary parameter

- changelog-entries/232.md
- elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp
> elastic-tube-1d: Remove unnecessary read statement

- elastic-tube-3d/fluid-openfoam/system/fvSolution
- turek-hron-fsi3/fluid-openfoam/system/fvSolution
I received a message on discourse pointing out that our hint for the ´residualControl` for OpenFOAM foundation versions is actually not correct. I added a note here and also a link to the corresponding OpenFOAM bug.
> Fix note regarding OpenFOAM and residual control

- partitioned-pipe/fluid1-openfoam-pimplefoam/system/controlDict
- partitioned-pipe/fluid1-openfoam-sonicliquidfoam/system/controlDict
- partitioned-pipe/fluid2-openfoam-pimplefoam/system/controlDict
- partitioned-pipe/fluid2-openfoam-sonicliquidfoam/system/controlDict
While running the partitioned-pipe in an OpenFOAM Adapter custom build, I noticed that the results were approx. 160MB in size, which is, I think, unreasonable for what we need.
This increases the `writeTime` from `0.01` to `0.1`. This is 10x fewer files, while 0.1s is still enough to capture the initial discontinuity (this may turn interesting later on in results comparisons).
I did not switch on results compression (i.e., making the output files binary), since eventually we may want to store them as reference results here and make some easy-to-check file comparisons, at least for the last time. If in the end we only check preCICE VTK files, we can enable compression everywhere.
@DavidSCN does this sound reasonable? Should we absolutely apply the same change to some other tutorial? If …
> Reduce the writing frquency of partitioned-pipe

- quickstart/README.md
This adds a few good resources for beginners to simulation software, Linux, Git, and more. @carlosal1015 suggested this during the preCICE Workshop 2022.
Apart from the recent SSE course by @uekerman/ @ajaust / @IshaanDesai, this also refers to previous related resources that cover a bit different content (but with quite some overlap). We should probably not keep adding links here, but really select the 2-3 most fitting resources for this use case.
@uekerman is there anything else you would like to see here?
After merging:
> Add resources for SSE basics

- elastic-tube-3d/fluid-openfoam/constant/dynamicMeshDict
- multiple-perpendicular-flaps/fluid-openfoam/constant/dynamicMeshDict
- perpendicular-flap/fluid-openfoam/constant/dynamicMeshDict
- quickstart/fluid-openfoam/constant/dynamicMeshDict
- turek-hron-fsi3/fluid-openfoam/constant/dynamicMeshDict
https://github.com/precice/openfoam-adapter/pull/222 adds support for OpenFOAM 9.
One of the changes that OpenFOAM 9 brought (not easily seen / clearly documented in the [release notes](https://openfoam.org/release/9/)) is the renaming of `solver` to `motionSolver` in `constant/dynamicMeshDict`.
Running our tutorials without renaming, will lead to the following error:
```
Selecting dynamicFvMesh dynamicMotionSolverFvMesh
--> FOAM FATAL IO ERROR: 
keyword motionSolver is undefined in dictionary "/home/vagrant/tutorials/perpendicular-flap/fluid-openfoam/constant/dynamicMeshDict"
file: /home/vagrant/tutorials/perpendicular-flap/fluid-openfoam/constant/dynamicMeshDict from line 9 to line 16.
From function T Foam::dictionary::lookup(const Foam::word&, bool, bool) const [with T = Foam::word]
in …
```
> Add note for motionSolver in OpenFOAM 9

- flow-over-heated-plate/solid-nutils/solid.py
- partitioned-heat-conduction/nutils/heat.py
The current active & stable nutils version is v7.0 (28ae68f3). With this pull request the first two examples are updated to nutils v7.0. At the moment the only change in this update is the way the libraries are imported. In order to have backward compatibility to previous nutils version, i.e., v6.3 (87281a0b), one needs to change only the importing style. The two styles of library import associated to the nutils version is demonstrated below.
nutils v7.0 (28ae68f3):
```python
from nutils import cli, solver
def main()
lhs = solver(...)
cli.run(main)
```
nutils v6.3 (87281a0b):
```python
import nutils
def main():
lhs = nutils.solver(...)
nutils.cli.run(main)
```
> Minor update to first two Nutils examples

- quickstart/README.md
In the quickstart guide change the download link of preCICE from 2.3.0 to 2.4.0
> Change preCICE version to latest version

- quickstart/solid-cpp/rigid_body_solver.cpp
using `std::pow` in a `constexpr` is not supported by Intel oneAPI C++ compiler:
```
rigid_body_solver.cpp(117): error: expression must have a constant value
constexpr double inertia_moment = (1. / 12) * mass * (4 * std::pow(length, 2) + std::pow(height, 2));
^
/usr/include/c++/8/cmath(418): note: cannot call non-constexpr function "pow" (declared at line 140 of "/usr/include/bits/mathcalls.h")
return pow(__type(__x), __type(__y));
^
```
> Remove std::pow from constexpr

- perpendicular-flap/solid-openfoam/system/preciceDict
- perpendicular-flap/solid-solids4foam/system/preciceDict
According to https://github.com/precice/openfoam-adapter/pull/252
Does not need a changelog entry (not previously released).
No clue why the PEP8 CI check fails, this does not touch any Python files.
> Rename force field name for solid participants

- partitioned-heat-conduction/nutils/heat.py
- partitioned-heat-conduction/nutils/run.sh
Some suggested changes to the heat.py script to make it more efficient, more correct, and hopefully easier to read, while remaining backwards compatible with nutils 6 as well as forwards compatible with nutils 8. The commit messages explain the reasoning behind the individual modifications.
> refactoring partitioned-heat-conduction/nutils

- partitioned-heat-conduction-direct/README.md
- partitioned-heat-conduction-direct/clean-tutorial.sh
- partitioned-heat-conduction-direct/nutils/clean.sh
- partitioned-heat-conduction-direct/nutils/heat.py
- partitioned-heat-conduction-direct/nutils/run.sh
- partitioned-heat-conduction-direct/precice-config.xml
- partitioned-heat-conduction/nutils/run.sh
> partitioned-heat-conduction: direct mesh access

- partitioned-heat-conduction/README.md
- partitioned-heat-conduction/fenicsx/clean.sh
- partitioned-heat-conduction/fenicsx/errorcomputation.py
- partitioned-heat-conduction/fenicsx/heat.py
- partitioned-heat-conduction/fenicsx/my_enums.py
- partitioned-heat-conduction/fenicsx/precice-adapter-config-D.json
- partitioned-heat-conduction/fenicsx/precice-adapter-config-N.json
- partitioned-heat-conduction/fenicsx/printStats.py
- partitioned-heat-conduction/fenicsx/problem_setup.py
- partitioned-heat-conduction/fenicsx/run.sh
This PR is to add a FEniCSx solver that is currently being developed at [https://github.com/precice/fenicsx-adapter](https://github.com/precice/fenicsx-adapter) to the partitioned-heat-equation tutorial. We opted for a minimal working release, so parallel runs and vector-valued functions are not yet supported.
> Adding FEniCSx solver to partitioned-heat-equation tutorial

- flow-over-heated-plate/tests/docker-compose.yml
Sometimes the cleanup service ran faster than the openfoam-adapter container leading to a missing "eth0" entry in the network configuration of the `precice-config.xml`
Now the [startup order](https://docs.docker.com/compose/startup-order/) is enforced via conditions.
> Fixed a docker-compose race condition

- elastic-tube-1d/fluid-cpp/run.sh
- elastic-tube-1d/solid-cpp/run.sh
The elastic-tube-1d cpp solvers require to be build inside `build` directories.
In-source builds don't work:
```
cd elastic-tube-1d/solid-cpp
cmake .
cmake --build .
./run.sh
Cannot find ./build/SolidSolver
```
This PR changes the run script to automatically configure and (re)build the solver.
@MakisH is this compatible with the VM?
> Build cpp solvers as part of run

- .markdownlint.json
Similarly to https://github.com/precice/openfoam-adapter/pull/290, this PR disables the markdown-lint check for bare URLs, as this now started complaining about the OpenFOAM copyright disclaimer.
As this rule is actually useful (especially for accessibility), an alternative would be to remove the `www.` part from the disclaimer.
> Markdown-lint: Disable MD034

- elastic-tube-3d/fluid-openfoam/system/fvSolution
- turek-hron-fsi3/fluid-openfoam/system/fvSolution
Adds outerCorrectorResidualControl dictionary adapted to fit OpenFOAM 9 requirements. Also modifies wrong dictionary name for OpenFOAM 6, 7, 8 ("outerResidualControl" changed to "outerCorrectorResidualControl")
I should specify I am not sure this change does not apply to older OpenFOAM versions, but I can confirm based on experience that OpenFOAM 9 will not run without the modified dictionary.
> Update fvSolution to fit OpenFOAM 9 and newer

- quickstart/README.md
Following https://github.com/precice/openfoam-adapter/pull/296.
> Quickstart: Update the recommended OpenFOAM version to v2306

- aste-turbine/precice-config.xml
- channel-transport-reaction/precice-config.xml
- channel-transport/precice-config.xml
- elastic-tube-1d/precice-config.xml
- elastic-tube-3d/precice-config.xml
- flow-over-heated-plate-nearest-projection/precice-config.xml
- flow-over-heated-plate-partitioned-flow/precice-config.xml
- flow-over-heated-plate-steady-state/precice-config.xml
- flow-over-heated-plate-two-meshes/precice-config.xml
- flow-over-heated-plate/precice-config.xml
- heat-exchanger-simplified/precice-config.xml
- heat-exchanger/precice-config.xml
- multiple-perpendicular-flaps/precice-config.xml
- oscillator/precice-config.xml
- partitioned-backwards-facing-step/precice-config.xml
- partitioned-elastic-beam/precice-config.xml
- partitioned-heat-conduction-complex/precice-config.xml
- partitioned-heat-conduction-direct/precice-config.xml
- partitioned-heat-conduction/precice-config.xml
- partitioned-pipe/precice-config.xml
- perpendicular-flap/precice-config.xml
- quickstart/precice-config.xml
- turek-hron-fsi3/precice-config.xml
- volume-coupled-diffusion/precice-config.xml
Following https://github.com/precice/precice/pull/1662
@davidscn please do a quick sanity check. I think that all other changes (that have already been merged in preCICE - the location of dimensions should follow) have been ported already.
> Remove XML tag solver-interface from all tutorials

- tools/tests/component-templates/fenics-adapter.yaml
- tools/tests/component-templates/nutils-adapter.yaml
- tools/tests/component-templates/openfoam-adapter.yaml
- tools/tests/docker-compose.template.yaml
- tools/tests/systemtests/Systemtest.py
This solves #354
Solution: 
- first get the User & Group ID of the current user via a subprocess call
- write out a .env file 
- docker compose will then use this and substitute ${UID} and ${GID}
It did not break the action:  see https://github.com/precice/tutorials/actions/runs/5740269267
> Fixed Docker compose root user problem #354

- tools/tests/README.md
- tools/tests/component-templates/fenics-adapter.yaml
- tools/tests/component-templates/nutils-adapter.yaml
- tools/tests/component-templates/openfoam-adapter.yaml
- tools/tests/components.yaml
- tools/tests/metadata_parser/metdata.py
- tools/tests/systemtests/Systemtest.py
In this PR i added preliminary support for the fenics adapter by using only the docker images published on docker hub. 
To execute it you can run the newly added fenics-test suite like: 
`python systemtests.py --suites=fenics-test`
I also renamed the build_arguments to be only called `build_arguments` and removed variations like `params` or `build_args` etc. 
This PR solves #352
> Add FEniCS adapter

- tools/tests/systemtests/Systemtest.py
In #356 it became obvious that we need to delete the folders if they have the same names as the script will fail. 
I opted against deletion because we want to be able to have them as artifacts later on. 
This PR solves #356 by introducing a timestamp to be added to the foldername. 
It also introduced a small .gitignore file to be places in the `run_directory` of the systemtests to not have 500 changed files show up in git.
> Added Timestamps to not override the folder

- tools/cleaning-tools.sh
Deletes the `./precice-events/` directory in each case.
Also removes the previously specified `precice-*-events.json` and `precice-*-events-summary.log`, as well as the relic `precice-postProcessingInfo.log`.
> Add precice-events to the cleaning scripts

- .github/workflows/run_testsuite.yml
- .github/workflows/run_testsuite_manual.yml
- .github/workflows/run_testsuite_workflow.yml
- tools/tests/README.md
- tools/tests/component-templates/calculix-adapter.yaml
- tools/tests/component-templates/fenics-adapter.yaml
- tools/tests/component-templates/nutils-adapter.yaml
- tools/tests/component-templates/openfoam-adapter.yaml
- tools/tests/docker-compose.field_compare.template.yaml
- tools/tests/docker-compose.template.yaml
- tools/tests/dockerfiles/ubuntu_2204/Dockerfile
- tools/tests/systemtests/Systemtest.py
This PR does some things: 
- adopt the dockerfile to work on ALL machines by specifing the host uid upon building time
- fetches the tutorial ref before trying to check that out (checkout-action doesnt do it)
- splits the testsuites runs into manual and reusable triggering
- introduce caching via GHA cache backend
> Add test workflows 

- partitioned-heat-conduction-complex/fenics/heat.py
- partitioned-heat-conduction-direct/nutils/heat.py
- partitioned-heat-conduction/fenicsx/heat.py
- partitioned-heat-conduction/nutils/heat.py
- partitioned-heat-conduction/openfoam-dirichlet/0.orig/T
- partitioned-heat-conduction/openfoam-dirichlet/setInitialField.sh
- partitioned-heat-conduction/openfoam-neumann/0.orig/T
- partitioned-heat-conduction/openfoam-neumann/setInitialField.sh
- partitioned-heat-conduction/openfoam-solver/heatTransfer.C
Closes https://github.com/precice/precice/commit/b8ba60bf8b6034d676aeec9e73bb366bebcfe848
Comments for the review: Am I missing some tutorial?
> Use beta consistent with literature

- partitioned-heat-conduction-complex/fenics/heat.py
- partitioned-heat-conduction/fenics/heat.py
Fixes bug, if time step changes inside window. See https://github.com/precice/fenics-adapter/issues/20.
For the purpose of documentation, if will add some comments in the diff of this PR.
With this bugfix the waveform version of the tutorial provided via #281 also works for non-matching subcycling, like described in https://github.com/precice/fenics-adapter/issues/20.
> Fix update of Dirichlet BC and RHS

- partitioned-heat-conduction/precice-config.xml
We should use nearest neighbor mapping here, because this is sufficient for this simple case with matching meshes. Also consistent with the description in the OpenFOAM adapter paper:
> Figure 6. ... The coupled scenario uses a nearest-neighbor mapping with matching interface nodes.
> Use `mapping:nearest-neighbor` in partitioned heat conduction

- partitioned-heat-conduction-complex/fenics/heat.py
- partitioned-heat-conduction/fenics/heat.py
I added in both examples Sympy expressions in the heat.py files and replaced the string representations of `u_D`, `f_N` and `f` with them.
If you want to change the analytical solution `u_D`, you now don't need to change anything else despite `u_D`. 
Before, it was necessary to change `f_N` and `f` but the expressions of both are now deduced from `u_D` automatically.
> Sympy expressions in partitioned-heat-conduction(-complex)

- flow-over-heated-plate-two-meshes/precice-config.xml
This was making preCICE complain when the Fluid participant was running in parallel.
See https://precice.discourse.group/t/problem-to-run-openfoam-in-parallel/1652
Previously:
> Bugfix: Remove stray mesh from flow-over-heated-plate-two-meshes

- .github/workflows/run_testsuite_workflow.yml
- tools/tests/systemtests/Systemtest.py
Executing `gh workflow run run_testsuite_manual.yml -f suites=fenics_test -f build_args="TUTORIALS_REF:hotfix-issue-399" -f loglevel=DEBUG 
-f systests_branch=hotfix-issue-399 --ref=hotfix-issue-399` [now works](https://github.com/precice/tutorials/actions/runs/6935990599). 
This should fix #399
> Hotfix issue 399

- tools/tests/README.md
Some more information:
- How to trigger the test manually from the GitHub CLI
- General architecture (first draft)
- What each relevant file is doing
Also removes the mention about `_TAG` naming rule, as I understand it is not used anywhere.
@valentin-seitz I would still like to add (but I am not yet sure how):
Maybe some of these need to go to separate issues.
> Update tests docs

- tools/tests/README.md
Adds metadata on the beginning of the page, to be able to render it on the website.
Related to https://github.com/precice/precice.github.io/pull/304
See also https://precice.org/docs-meta-overview.html#rendering-content-from-external-repositories
> System tests docs: Add metadata for the website

- aste-turbine/clean.sh
- tools/clean-tutorial-base.sh
- tools/cleaning-tools.sh
As mentioned in the title. I noticed this in the cleaning logs while creating a new tutorial.
> Remove unnecessary `clean_aste` call from base cleaning

- perpendicular-flap/solid-fenics/solid.py
This PR fixes the broken autopep8 Pipeline, which broke overnight :)
Apparently some illegal character placed itself there in the whitespace, which needed to be removed :)
> Fix broken autopep8 Pipeline

- tools/tests/systemtests/Systemtest.py
This PR adds some hotfixes for non terminating Systemtests
> Fix non terminating timeouts

- .github/workflows/check-markdown.yml
- .github/workflows/check-pep8.yml
- .github/workflows/check-scripts.yaml
Currently the checks for markdown linting, pep8, and scripts are run twice for every push or pull requests to the master or develop branch. For example:
By setting the branches explicitly in the workflows, we can ensure that the workflows are run only once.
> Run checks for markdown linting, pep8, and scripts only once for push and pull requests

- elastic-tube-1d/metadata.yaml
- elastic-tube-1d/reference-data/fluid-cpp_solid-cpp.tar.gz
- elastic-tube-1d/reference-data/fluid-cpp_solid-python.tar.gz
- elastic-tube-1d/reference-data/fluid-python_solid-python.tar.gz
- elastic-tube-1d/reference_results.metadata
- flow-over-heated-plate/reference-results/fluid-openfoam_solid-fenics.tar.gz
- flow-over-heated-plate/reference-results/fluid-openfoam_solid-nutils.tar.gz
- flow-over-heated-plate/reference-results/fluid-openfoam_solid-openfoam.tar.gz
- perpendicular-flap/reference-results/fluid-openfoam_solid-calculix.tar.gz
- perpendicular-flap/reference_results.metadata
- tools/tests/component-templates/bare.yaml
- tools/tests/component-templates/python-bindings.yaml
- tools/tests/components.yaml
- tools/tests/dockerfiles/ubuntu_2204/Dockerfile
- tools/tests/tests.yaml
Adds a test suite for `elastic-tube-1d`, which is a special case, since it does not rely on any adapter (but relies partially on the python-bindings).
Overview of changes:
- New component `bare`, which essentially only relies on the `precice` Docker image.
- New component `python-bindings`
- Adds a `metadata.yml` into the `elastic-tube-1d` tutorial
- Defines the test suite `elastic_tube_1d_test`, with the tests:
- fluid-cpp x solid-cpp: Test the C++ API
- fluid-python x solid-python: Test the Python API
- fluid-cpp x solid-python: Test the interoperability between C++ and Python
However, only the last test is being executed: https://github.com/precice/tutorials/issues/394
This test correctly fails to build the code and run the simulation when executing `generate_reference_data.py`, since …
> Add test elastic-tube-1d tests

- .github/workflows/run_testsuite_workflow.yml
Since this workflow is reusable and can be called my multiple repos and default value is ${{ github.repository }}. This poses a problem as the action will check out the calling repository, which is not what we want if the calling repo is e.g. the openfoam-adapter.
> Specify right repository

- perpendicular-flap/README.md
- perpendicular-flap/solid-nutils/clean.sh
- perpendicular-flap/solid-nutils/run.sh
- perpendicular-flap/solid-nutils/solid.py
This PR adds a solid participant compatible only with Nutils 8, formerly part of #429.
It's a draft for now because it was discovered that the system has more damping than reference results, potentially resulting from the fully implicit first order formulation. I will do some more testing in the coming days to try and sort this out.
> add nutils solid participant

- elastic-tube-1d/fluid-cpp/CMakeLists.txt
- elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp
- elastic-tube-1d/fluid-python/FluidSolver.py
- elastic-tube-1d/precice-config.xml
- elastic-tube-1d/solid-cpp/CMakeLists.txt
- elastic-tube-1d/solid-cpp/src/SolidComputeSolution.cpp
- elastic-tube-1d/solid-cpp/src/SolidSolver.cpp
- elastic-tube-1d/solid-python/SolidSolver.py
This PR ports the elastic-tube-1d cpp solvers to version 3
This also rearranges the solvers to follow the pattern read data -> solve -> write data -> advance.
Also fixes the incorrect coordinates in solid-cpp #340
> Port elastic-tube-1d solvers to version 3

- tools/tests/docker-compose.template.yaml
This PR introduces a fix that enables to rewrite the `precice-config.xml `for both v2 and v3 versions. 
Since the word “from” does not appear, sed should now be able to set the network used for systemtests accordingly.
> Fix: Participants could not find each other during the systemtests

- channel-transport/fluid-nutils/fluid.py
- channel-transport/transport-nutils/transport.py
- flow-over-heated-plate/solid-nutils/solid.py
- partitioned-heat-conduction-direct/nutils/heat.py
- partitioned-heat-conduction/nutils/heat.py
- perpendicular-flap/fluid-nutils/fluid.py
- two-scale-heat-conduction/macro-nutils/macro.py
- volume-coupled-flow/source-nutils/source.py
I updated the tutorials to follow the pattern suggested in our adapterexample. In some cases, the implementation of subcylcling was also buggy.
@uekerman, @IshaanDesai : Especially a `dt = min(dt, precice_dt)` is very dangerous in the context of subcycling and can lead to errors that are very hard to find. I did not run the cases that I touched. Please do a quick check for the cases that you feel responsible for.
> Fix subcycling

- oscillator/plot-trajectory.py
For the newer `pandas` version(2.2.0 for my instance), it requires the data to be converted to a numpy array before indexing for plotting with `matplotlib.pyplot.plot()`. Otherwise it gives error like:
```
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```
The `plot-trajectory.py` in the tutorial case `oscillator` is this case.
> Solve compatibility issue by using pandas newer version and matplotlib for plotting

- .pre-commit-config.yaml
- tools/check-image-names.py
This PR adds a pre-commit hook that checks if the names of images in `A/images/` are correctly prefixed.
The required prefix is: `tutorial-<A>-` or `quickstart-` if `A` is `quickstart`.
This is required to prevent conflicts in the website assets folder.
> Add hook to check image names

- flow-around-controlled-moving-cylinder/README.md
- oscillator/README.md
The old one was linking to the complete proceedings as a placeholder. Now, individual DOIs were given.
> Update DOI of FMI paper

- perpendicular-flap/README.md
- perpendicular-flap/plot-all-displacements.sh
Very use-case-specific, outdated, and trivial to reproduce from plot-displacement.sh
> Document script plot-all-displacements

- elastic-tube-3d/solid-fenics/solid.py
- perpendicular-flap/solid-fenics/solid.py
I took too much liberty in #505 and removed some code that was not supposed to be removed, and merged before confirming. This PR reverts that change.
FYI @BenjaminRodenberg 
I will test the cases and merge, even if I don't get a review until then, since I am currently trying to disentangle a bunch of inter-dependent work packages. Please complain again if you spot any mistakes.
> Revert some of the ufl-relateve changes from #505

- two-scale-heat-conduction/micro-nutils/micro-manager-config.json
- two-scale-heat-conduction/micro-nutils/micro.py
This PR removes the initial correction calculation of the phase field in the `micro-nutils` participant of the two-scale-heat-conduction tutorial. This calculation was originally implemented so that the micro simulation will start with a very accurate grain description. However, if the micro structure (grain) is not represented extremely accurately, the resultant phase field and the average porosity will still yield sensible values. Therefore this calculation can be commented out to cut down the initialization time and make the `micro-nutils` participant faster.
- On 4 processors: 6.5 minutes
- On 2 processors: 10.5 minutes
> Make Nutils participant `micro-nutils` in the two-scale-heat-conduction tutorial faster

- two-scale-heat-conduction/README.md
- two-scale-heat-conduction/micro-dumux/appl/micro_sim.cpp
- two-scale-heat-conduction/setup-dumux.sh
Some fixes to the two-scale-heat-conduction tutorial.
- Changes due to an update in the Micro-Manager (v0.4.0)
- Changes in the script `setup-dumux.sh` to make it more robust.
> Fix two scale heat conduction
